[phases.setup]
nixPkgs = ['nodejs-18_x', 'npm-8_x']

[phases.build]
cmds = ['cd backend && npm ci && npm run build']

[phases.start]
cmd = 'cd backend && npm start'

[variables]
NODE_ENV = 'production'