[phases.setup]
nixPkgs = ['nodejs-20_x', 'npm-10_x']

[variables]
NODE_ENV = 'production'
SUPABASE_URL = 'https://sgbjhwhwnldhgcydqqny.supabase.co'
SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNnYmpod2h3bmxkaGdjeWRxcW55Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwMzc5MTEsImV4cCI6MjA3MTYxMzkxMX0.X7FMI_tNPsC7U0ZBzhYKZ3nsCbbrzMkbNH37C0HP2VE'